
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Ra9841754305!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    cache-names:
      - cache1
      - cache2
    redis:
      time-to-live: 3600000  # 1 hour
      cache-null-values: true
